USE [POLEWVWEBPRD]
GO
/****** Object:  StoredProcedure [dbo].[PRWVIMPORTAPEDIDO]    Script Date: 02/05/2024 09:46:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[PRWVIMPORTAPEDIDO]
(
    @CDEMPRESA VARCHAR(20),
    @CDREPRESENTANTE VARCHAR(20),
    @RETORNO VARCHAR(4000) OUTPUT
) AS
BEGIN

	SET @RETORNO = 'OK';

	DECLARE @NUPEDIDO VARCHAR(30),
			@FLORIGEMPEDIDO CHAR(1),
			@CDORGVENDA VARCHAR(20),
			@CDORGVENDAFERT VARCHAR(20),
			@CDORGVENDAHAWA VARCHAR(20),
			@VLTOTAL DECIMAL(16, 7),
			@CDLINHA VARCHAR(20),
			@QTD INT;

	/*Separar Pedidos Antes do WebService Enviar os Pedidos*/

	BEGIN TRY

		DECLARE SEP_PEDIDO CURSOR LOCAL FOR
			
			SELECT
				PED.FLORIGEMPEDIDO,
				PED.NUPEDIDO,
				COALESCE(CLI.CDCANALCLIENTE, '0') AS CDORGVENDA
			FROM TBLVWPEDIDO PED
			JOIN TBLVWCLIENTE CLI
				ON PED.CDEMPRESA = CLI.CDEMPRESA
				AND PED.CDREPRESENTANTE = CLI.CDREPRESENTANTE
				AND PED.CDCLIENTE = CLI.CDCLIENTE
			WHERE
				PED.CDEMPRESA = @CDEMPRESA
			AND PED.CDREPRESENTANTE = @CDREPRESENTANTE
			AND (COALESCE(PED.FLENVIADOPROTOCOLO, 'N') <> 'S')
			AND COALESCE(FLCONTROLEERP,'X') <> 'E';

		OPEN SEP_PEDIDO;		
		FETCH NEXT FROM SEP_PEDIDO INTO @FLORIGEMPEDIDO, @NUPEDIDO, @CDORGVENDA
		WHILE @@FETCH_STATUS = 0
		BEGIN

			SET @CDORGVENDAFERT = NULL;
			SET @CDORGVENDAHAWA = NULL;
					
			BEGIN TRAN;

		UPDATE TBLVWPEDIDO 
			SET NUORDEMCOMPRACLIENTE = dbo.TRANSLATE(NUORDEMCOMPRACLIENTE,'áâãäæèïéìëíîçÇåñòóôöõàøúüûùýÁÂÃÄÆÈÏÉÌËÍÎÅÑÒÓÔÖÕÀØÚÜÛÙÝ','aaaaeeieieiicCanoooooaouuuuyAAAAAEIEIEIIANOOOOOAOUUUUY')
			WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE
			
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO;
				
			UPDATE ITE
			SET CDLINHA = PRO.CDCOLECAO 
			FROM TBLVWITEMPEDIDO ITE
			JOIN TBLVWPRODUTO PRO
				ON ITE.CDEMPRESA = PRO.CDEMPRESA
				AND PRO.CDREPRESENTANTE = CAST('0' AS VARCHAR(20))
				AND ITE.CDPRODUTO = PRO.CDPRODUTO
			WHERE
				ITE.CDEMPRESA = @CDEMPRESA 
			AND ITE.CDREPRESENTANTE = @CDREPRESENTANTE
			AND ITE.FLORIGEMPEDIDO = @FLORIGEMPEDIDO
			AND ITE.NUPEDIDO = @NUPEDIDO;
				
			SELECT
				@QTD = COUNT(DISTINCT CDLINHA)
			FROM TBLVWITEMPEDIDO 
			WHERE
				CDEMPRESA = @CDEMPRESA
			AND CDREPRESENTANTE = @CDREPRESENTANTE
			AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
			AND NUPEDIDO = @NUPEDIDO;
			
			SELECT
				@CDORGVENDAFERT = RTRIM(COALESCE(CDORGVENDA, '0'))
			FROM ERPINTORGVENDAPRODUTO
			WHERE 
				CDTIPOPRODUTO = 'FERT'
			AND CDORGVENDA IN (SUBSTRING(@CDORGVENDA, 1, 4), SUBSTRING(@CDORGVENDA, 6, 4));
				
			SELECT @CDORGVENDAHAWA = RTRIM(COALESCE(CDORGVENDA, '0'))
			FROM ERPINTORGVENDAPRODUTO
			WHERE 
				CDTIPOPRODUTO = 'HAWA'
			AND CDORGVENDA IN (SUBSTRING(@CDORGVENDA, 1, 4), SUBSTRING(@CDORGVENDA, 6, 4));

			IF @QTD > 1
			BEGIN
					
				UPDATE TBLVWPEDIDO
				SET CDORGVENDA = @CDORGVENDAFERT
				WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE 
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO; 

				--QUEBRA PEDIDO 
				INSERT INTO TBLVWPEDIDO (
					CDEMPRESA, CDREPRESENTANTE, FLORIGEMPEDIDO, NUPEDIDO, CDCLIENTE, CDCONDICAOPAGAMENTO, CDTABELAPRECO,
					CDTRANSPORTADORA, CDTIPOSERVICOFRETE, CDTIPOPAGAMENTO, CDTIPOPEDIDO, DTEMISSAO, HREMISSAO,
					DTENTREGA, NUORDEMCOMPRACLIENTE, VLFRETE, CDSTATUSPEDIDO, VLPCTDESCONTO, VLPCTDESCPROGRESSIVO,
					VLDESCONTO, VLTOTALPEDIDO, VLBONIFICACAOPEDIDO, VLTROCARECOLHER, VLTROCAENTREGAR, QTPESO,
					DSMENSAGEMENTREGA, DSOBSERVACAO, DSOBSERVACAONOTAFISCAL, DSCONDICAOPAGAMENTOSEMCADASTRO,
					VLTOTALITENS, VLRENTABILIDADE, VLIPI, VLIPIFRETE, QTDIASPAGAMENTO, NUSUFRAMA, NUROTAENTREGA,
					NULOTEENTREGA, FLCONDICAOPGTOLIBERADOSENHA, FLPRECOLIBERADOSENHA, FLCLIENTEATRASADOLIBERADOSENHA,
					FLCREDITOCLIENTELIBERADOSENHA, FLTIPOPEDIDOLIBERADOSENHA, FLPEDIDONOVOCLIENTE, NUPEDIDORELACIONADO,
					FLORIGEMPEDIDORELACIONADO, DTRECEBIMENTO, HRRECEBIMENTO, DTENVIOERP, HRENVIOERP, CDSUPERVISOR, NUVERSAOSISTEMAORIGEM,
					FLIMPRESSO, FLEMAILENVIADO, FLCONTROLEERP, DSMENSAGEMCONTROLEERP, FLCONTROLEWMW, DSMENSAGEMCONTROLEWMW, VLVERBAPEDIDO,
					VLVERBAPEDIDOPOSITIVO, FLPOSSUIDIFERENCA, HRFIMEMISSAO, CDROTAENTREGA, CDTIPOENTREGA, CDSETOR,
					CDORIGEMSETOR, CDAREAVENDA, DTFECHAMENTO, QTPONTOSPEDIDO, HRFECHAMENTO, DTTRANSMISSAOPDA, HRTRANSMISSAOPDA,
					CDOPORTUNIDADE, CDUSUARIOEMISSAO, CDCONTATO, CDMOTIVOCANCELAMENTO, NMCONTATOCANCELAMENTO, NUFONECONTATOCANCELAMENTO,
					VLCOTACAODOLAR, DSDESTINO, VLPCTDESCITEM, NUPEDIDOREDUZIDO, CDMEIOCOMUNICACAO, VLTOTALBRUTOITENS, FLBLOQUEADOEDICAO,
					CDSEGMENTO, FLEDITANDO, FLMAXVENDALIBERADOSENHA, CDUSUARIOLIBERACAO, DSMOTIVODESCONTO, CDCONDICAOCOMERCIAL,
					FLPEDIDOREABERTO, VLPCTFRETEREPRESENTANTE, VLFRETEREPRESENTANTE, VLFRETECLIENTE, NUPEDIDOSUGESTAO,
					FLORIGEMPEDIDOSUGESTAO, NUPEDIDORELBONIFICACAO, VLTOTALPEDIDOESTOQUEPOSITIVO, CDCENTROCUSTO, CDITEMCONTA,
					CDCLASSEVALOR, FLEMAILSTATUSALTERADOENVIADO, DSURLENVIOSERVIDOR, FLPEDIDOREPLICADO, NUPEDIDOORIGINAL,
					FLSUGESTAOVENDALIBERADOSENHA, CDCARGAPEDIDO, FLABAIXORENTABILIDADEMINIMA, FLEMAILERROINTEGRACAOENVIADO,
					FLENVIAEMAIL, CDATENDIMENTO, VLPCTMARGEMMIN, FLETAPAVERBA, FLCALCULAVERBAGRUPOSALDO, VLPCTCOMISSAO,
					FLPAGAMENTOAVISTA, FLGERANFE, NUKMINICIAL, NUKMFINAL, HRINICIALINDICADO, HRFINALINDICADO, FLNFEIMPRESSA,
					FLETAPAVERBAANTERIOR, FLLIBERADOENTREGA, CDENDERECOCLIENTE, FLGERABOLETO, FLBOLETOIMPRESSO,
					FLSITUACAORESERVAEST, NUPEDIDOCOMPLEMENTADO, NUPEDIDORELTROCA, FLKEYACCOUNT, FLEMERGENCIAL,
					CDMOTIVOEMERGENCIA, DSOBSEMERGENCIA, CDUSUARIOAUTORIZACAO, NUPEDIDORELEMERGENCIAL, FLPENDENTE,
					CDMOTIVOACRESCIMOCUSTO, VLPCTACRESCIMOCUSTO, CDCOTACAO, FLGERACREDITOFRETE, VLTOTALCREDITOFRETE,
					FLGERACREDITOCONDICAO, VLTOTALCREDITOCONDICAO, FLVISIVEL, VLTOTALBASEITENS, FLITEMPENDENTE,
					VLPCTDESCPROGRESSIVOMIX, CDVERBAUTILIZACAO, VLVOLUMEPEDIDO, VLPCTDESCCLIENTE, VLPCTDESCONTOCONDICAO, VLPCTDESCFRETE,
					CDTIPOFRETE, CDCUPOM, VLPCTDESCONTOCUPOM, VLDESCONTOCUPOM, VLTOTALTROCAPEDIDO, DSEMAILSDESTINO,
					DTENTREGALIBERADA, DTCARREGAMENTO, FLCOTACONDPAGTO, CDUSUARIOLIBENTREGA, CDCLIENTEENTREGA,
					FLRESTRITO, NUPEDCOMPRELACIONADO, FLMINVERBALIBERADO, CDCONDNEGOCIACAO, CDUNIDADE, DTCONSIGNACAO,
					VLPEDIDOORIGINAL, VLTOTALDEVOLUCOES, FLCONSIGNACAOIMPRESSA, FLNFECONTIMPRESSA, CDPEDIDOSAGRUPADOS,
					CDREGIAO, CDENTREGA, CDTRANSPORTADORAAUX, FLEMAILLIBERACAOENVIADO, FLRENTABILIDADELIBERADA, FLPROMISSORIAIMPRESSA,
					VLTOTALMARGEM, CDATENDIMENTOATIVIDADE, FLSALDOBONILIBERADOSENHA, VLPCTDESC2, VLPCTDESC3, DHCONFIRMACAOESTOQUE,
					NUCNPJTRANSPORTADORA, CDSTATUSORCAMENTO, FLMODOESTOQUE, DTPAGAMENTO, FLPEDIDOERPVIGENTE, FLVENDAASSISTIDA,
					CDTRIBUTACAOCLIENTE, FLPEDIDODIFERENCA, NUPEDIDODIFERENCA, VLPCTINDICEFINCONDPAGTO, VLPCTDESCQUANTIDADEPESO,
					DSJUSTIFICATIVACANCELAMENTO, FLDESCONTOLIBERADOSENHA, FLPROCESSANDONFETXT, FLAGUARDAPEDIDOCOMPLEMENTAR,
					DTULTIMORECALCULOVALORES, VLPCTVPC, NULOTEPROTOCOLO, FLENVIADOPROTOCOLO, VLTOTALNOTACREDITO,
					VLDESCONTOINDICEFINANCLIENTE, DSOBSORCAMENTO, DSMOTIVOCANCLIMCREDITO, FLPENDENTELIMCRED, CDUSUARIOCANCLIMCRED,
					CDUSUARIOLIBERACAOLIMCRED, VLPCTDESCONTOAUTOEFETIVO, VLDESCONTOTOTALAUTODESC, VLTOTALDESCONTOAUTO, FLATIVO,
					FLTIPOALTERACAO, DTALTERACAO, HRALTERACAO, FLCONTROLEEMISSAONFE, QTENCOMENDA, VLTOTALENCOMENDA,
					CDCOMISSAOPEDIDOREP, FLVALORMINPARCELALIBERADOSENHA, CDLOCALESTOQUE, NUPEDIDOREFERENCIA,
					VLSEGUROPEDIDO, DSOBSERVACAOCLIENTE, VLPCTTOTALMARGEM, QTDIASCPGTOLIBSENHA, VLTOTALPEDIDOLIBERADO,
					VLPCTDESCHISTORICOVENDAS, DSMOTIVOBONIFICACAO, VLVERBAFORNECEDOR, VLVERBAGRUPO, FLCALCULASEGURO,
					CDLOCAL, CDFRETECONFIG, CDMODOFATURAMENTO, DSOBSMODOFATURAMENTO, CDPLATAFORMAVENDA, CDREPRESENTANTEORG,
					CDCONTACORRENTE, DTVERBASALDOCALCULADA, VLTOTALPONTUACAOBASE, VLTOTALPONTUACAOREALIZADO, 
					CDENDERECOCOBRANCA, NUPARCELAS, FLPEDIDOLIBERADOOUTRAORDEM, FLGONDOLA, VLBASEMARGEMRENTAB, VLCUSTOMARGEMRENTAB,
					VLPCTMARGEMRENTAB, CDMOTIVOREGISTROVISITA, CDREPORIGINAL, CDORGVENDA
				)
				SELECT
					CDEMPRESA, CDREPRESENTANTE, FLORIGEMPEDIDO, CONCAT('A', NUPEDIDO), CDCLIENTE, CDCONDICAOPAGAMENTO, CDTABELAPRECO,
					CDTRANSPORTADORA, CDTIPOSERVICOFRETE, CDTIPOPAGAMENTO, CDTIPOPEDIDO, DTEMISSAO, HREMISSAO,
					DTENTREGA, NUORDEMCOMPRACLIENTE, VLFRETE, CDSTATUSPEDIDO, VLPCTDESCONTO, VLPCTDESCPROGRESSIVO,
					VLDESCONTO, VLTOTALPEDIDO, VLBONIFICACAOPEDIDO, VLTROCARECOLHER, VLTROCAENTREGAR, QTPESO,
					DSMENSAGEMENTREGA, DSOBSERVACAO, DSOBSERVACAONOTAFISCAL, DSCONDICAOPAGAMENTOSEMCADASTRO,
					VLTOTALITENS, VLRENTABILIDADE, VLIPI, VLIPIFRETE, QTDIASPAGAMENTO, NUSUFRAMA, NUROTAENTREGA,
					NULOTEENTREGA, FLCONDICAOPGTOLIBERADOSENHA, FLPRECOLIBERADOSENHA, FLCLIENTEATRASADOLIBERADOSENHA,
					FLCREDITOCLIENTELIBERADOSENHA, FLTIPOPEDIDOLIBERADOSENHA, FLPEDIDONOVOCLIENTE, NUPEDIDORELACIONADO,
					FLORIGEMPEDIDORELACIONADO, DTRECEBIMENTO, HRRECEBIMENTO, DTENVIOERP, HRENVIOERP, CDSUPERVISOR, NUVERSAOSISTEMAORIGEM,
					FLIMPRESSO, FLEMAILENVIADO, FLCONTROLEERP, DSMENSAGEMCONTROLEERP, FLCONTROLEWMW, DSMENSAGEMCONTROLEWMW, VLVERBAPEDIDO,
					VLVERBAPEDIDOPOSITIVO, FLPOSSUIDIFERENCA, HRFIMEMISSAO, CDROTAENTREGA, CDTIPOENTREGA, CDSETOR,
					CDORIGEMSETOR, CDAREAVENDA, DTFECHAMENTO, QTPONTOSPEDIDO, HRFECHAMENTO, DTTRANSMISSAOPDA, HRTRANSMISSAOPDA,
					CDOPORTUNIDADE, CDUSUARIOEMISSAO, CDCONTATO, CDMOTIVOCANCELAMENTO, NMCONTATOCANCELAMENTO, NUFONECONTATOCANCELAMENTO,
					VLCOTACAODOLAR, DSDESTINO, VLPCTDESCITEM, NUPEDIDOREDUZIDO, CDMEIOCOMUNICACAO, VLTOTALBRUTOITENS, FLBLOQUEADOEDICAO,
					CDSEGMENTO, FLEDITANDO, FLMAXVENDALIBERADOSENHA, CDUSUARIOLIBERACAO, DSMOTIVODESCONTO, CDCONDICAOCOMERCIAL,
					FLPEDIDOREABERTO, VLPCTFRETEREPRESENTANTE, VLFRETEREPRESENTANTE, VLFRETECLIENTE, NUPEDIDOSUGESTAO,
					FLORIGEMPEDIDOSUGESTAO, NUPEDIDORELBONIFICACAO, VLTOTALPEDIDOESTOQUEPOSITIVO, CDCENTROCUSTO, CDITEMCONTA,
					CDCLASSEVALOR, FLEMAILSTATUSALTERADOENVIADO, DSURLENVIOSERVIDOR, FLPEDIDOREPLICADO, NUPEDIDOORIGINAL,
					FLSUGESTAOVENDALIBERADOSENHA, CDCARGAPEDIDO, FLABAIXORENTABILIDADEMINIMA, FLEMAILERROINTEGRACAOENVIADO,
					FLENVIAEMAIL, CDATENDIMENTO, VLPCTMARGEMMIN, FLETAPAVERBA, FLCALCULAVERBAGRUPOSALDO, VLPCTCOMISSAO,
					FLPAGAMENTOAVISTA, FLGERANFE, NUKMINICIAL, NUKMFINAL, HRINICIALINDICADO, HRFINALINDICADO, FLNFEIMPRESSA,
					FLETAPAVERBAANTERIOR, FLLIBERADOENTREGA, CDENDERECOCLIENTE, FLGERABOLETO, FLBOLETOIMPRESSO,
					FLSITUACAORESERVAEST, NUPEDIDOCOMPLEMENTADO, NUPEDIDORELTROCA, FLKEYACCOUNT, FLEMERGENCIAL,
					CDMOTIVOEMERGENCIA, DSOBSEMERGENCIA, CDUSUARIOAUTORIZACAO, NUPEDIDORELEMERGENCIAL, FLPENDENTE,
					CDMOTIVOACRESCIMOCUSTO, VLPCTACRESCIMOCUSTO, CDCOTACAO, FLGERACREDITOFRETE, VLTOTALCREDITOFRETE,
					FLGERACREDITOCONDICAO, VLTOTALCREDITOCONDICAO, FLVISIVEL, VLTOTALBASEITENS, FLITEMPENDENTE,
					VLPCTDESCPROGRESSIVOMIX, CDVERBAUTILIZACAO, VLVOLUMEPEDIDO, VLPCTDESCCLIENTE, VLPCTDESCONTOCONDICAO, VLPCTDESCFRETE,
					CDTIPOFRETE, CDCUPOM, VLPCTDESCONTOCUPOM, VLDESCONTOCUPOM, VLTOTALTROCAPEDIDO, DSEMAILSDESTINO,
					DTENTREGALIBERADA, DTCARREGAMENTO, FLCOTACONDPAGTO, CDUSUARIOLIBENTREGA, CDCLIENTEENTREGA,
					FLRESTRITO, NUPEDCOMPRELACIONADO, FLMINVERBALIBERADO, CDCONDNEGOCIACAO, CDUNIDADE, DTCONSIGNACAO,
					VLPEDIDOORIGINAL, VLTOTALDEVOLUCOES, FLCONSIGNACAOIMPRESSA, FLNFECONTIMPRESSA, CDPEDIDOSAGRUPADOS,
					CDREGIAO, CDENTREGA, CDTRANSPORTADORAAUX, FLEMAILLIBERACAOENVIADO, FLRENTABILIDADELIBERADA, FLPROMISSORIAIMPRESSA,
					VLTOTALMARGEM, CDATENDIMENTOATIVIDADE, FLSALDOBONILIBERADOSENHA, VLPCTDESC2, VLPCTDESC3, DHCONFIRMACAOESTOQUE,
					NUCNPJTRANSPORTADORA, CDSTATUSORCAMENTO, FLMODOESTOQUE, DTPAGAMENTO, FLPEDIDOERPVIGENTE, FLVENDAASSISTIDA,
					CDTRIBUTACAOCLIENTE, FLPEDIDODIFERENCA, NUPEDIDODIFERENCA, VLPCTINDICEFINCONDPAGTO, VLPCTDESCQUANTIDADEPESO,
					DSJUSTIFICATIVACANCELAMENTO, FLDESCONTOLIBERADOSENHA, FLPROCESSANDONFETXT, FLAGUARDAPEDIDOCOMPLEMENTAR,
					DTULTIMORECALCULOVALORES, VLPCTVPC, NULOTEPROTOCOLO, FLENVIADOPROTOCOLO, VLTOTALNOTACREDITO,
					VLDESCONTOINDICEFINANCLIENTE, DSOBSORCAMENTO, DSMOTIVOCANCLIMCREDITO, FLPENDENTELIMCRED, CDUSUARIOCANCLIMCRED,
					CDUSUARIOLIBERACAOLIMCRED, VLPCTDESCONTOAUTOEFETIVO, VLDESCONTOTOTALAUTODESC, VLTOTALDESCONTOAUTO, FLATIVO,
					FLTIPOALTERACAO, DTALTERACAO, HRALTERACAO, FLCONTROLEEMISSAONFE, QTENCOMENDA, VLTOTALENCOMENDA,
					CDCOMISSAOPEDIDOREP, FLVALORMINPARCELALIBERADOSENHA, CDLOCALESTOQUE, NUPEDIDOREFERENCIA,
					VLSEGUROPEDIDO, DSOBSERVACAOCLIENTE, VLPCTTOTALMARGEM, QTDIASCPGTOLIBSENHA, VLTOTALPEDIDOLIBERADO,
					VLPCTDESCHISTORICOVENDAS, DSMOTIVOBONIFICACAO, VLVERBAFORNECEDOR, VLVERBAGRUPO, FLCALCULASEGURO,
					CDLOCAL, CDFRETECONFIG, CDMODOFATURAMENTO, DSOBSMODOFATURAMENTO, CDPLATAFORMAVENDA, CDREPRESENTANTEORG,
					CDCONTACORRENTE, DTVERBASALDOCALCULADA, VLTOTALPONTUACAOBASE, VLTOTALPONTUACAOREALIZADO, 
					CDENDERECOCOBRANCA, NUPARCELAS, FLPEDIDOLIBERADOOUTRAORDEM, FLGONDOLA, VLBASEMARGEMRENTAB, VLCUSTOMARGEMRENTAB,
					VLPCTMARGEMRENTAB, CDMOTIVOREGISTROVISITA, CDREPORIGINAL, @CDORGVENDAHAWA
				FROM TBLVWPEDIDO
				WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE 
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO; 

				INSERT INTO TBLVWITEMPEDIDO (
					CDEMPRESA, CDREPRESENTANTE, FLORIGEMPEDIDO, NUPEDIDO, CDPRODUTO, FLTIPOITEMPEDIDO,
					NUSEQPRODUTO, NUSEQITEMPEDIDO, CDTABELAPRECO, CDITEMGRADE1, CDITEMGRADE2, CDITEMGRADE3,
					QTITEMFISICO, QTITEMFATURAMENTO, VLITEMPEDIDO, VLBASEITEMTABELAPRECO, VLBASEITEMPEDIDO, VLBASEFLEX,
					VLTOTALITEMPEDIDO, VLPCTDESCONTO, VLPCTACRESCIMO, VLPCTDESCONTOFOB, VLPCTIPIITEM, VLIPIITEM,
					VLRENTABILIDADE, NULISTATABELAPRECO, QTTROCAESPECIAL, VLUNIDADEPADRAO, VLBASEEMBALAGEMELEMENTAR, FLCONTROLEERP,
					DSMENSAGEMCONTROLEERP, DSMENSAGEMCONTROLEWMW, CDGRUPOBONIFICACAO, CDLINHA, VLVERBAITEM, CDCONTACORRENTE,
					CDKIT, CDLOTEPRODUTO, VLITEMPEDIDOFRETE, QTPONTOSITEM, VLPCTIPIITEMFRETE, VLIPIITEMFRETE,
					CDMOTIVOTROCA, CDUNIDADE, DSOBSMOTIVOTROCA, VLST, VLVERBAITEMPOSITIVO, QTPESO, DSOBSERVACAO,
					VLPCTCOMISSAO, FLPRECOLIBERADOSENHA, VLREDUCAOOPTANTESIMPLES, VLTOTALBRUTOITEMPEDIDO, FLORIGEMITEMPEDIDO,
					FLVENDIDOQTMINIMA, CDPRAZOPAGTOPRECO, QTITEMPEDIDOUNELEMENTAR, VLITEMPEDIDOUNELEMENTAR, FLMETAGRUPOPRODLIBERADOSENHA,
					VLFRETE, FLLIBERADOVENDARELACIONADA, QTITEMESTOQUEPOSITIVO, VLDESCONTOCCP, VLPCTDESCONTOCCP, NUPROMOCAO,
					VLFINALPROMO, VLDESCONTOPROMO, VLPCTDESCONTOPROMO, VLPCTFAIXADESCQTD, VLFECOP, VLICMS,
					VLPIS, VLCOFINS, VLDESPESAACESSORIA, VLDESCONTO, VLPCTDESCONTO2, VLDESCONTO2, VLPCTDESCONTO3, VLDESCONTO3,
					CDSUGESTAOVENDA, VLTOTALITEMPEDIDOFRETE, VLPCTDESCONTOCANAL, CDTRIBUTACAOCONFIG, DTINICIOPROMOCAO,
					CDVERBAGRUPO, VLTOTALSTITEM, VLTOTALIPIITEM, VLTOTALICMSITEM, VLTOTALPISITEM, VLTOTALCOFINSITEM,
					VLSEGUROITEMPEDIDO, CDUSUARIOLIBERACAO, FLESTOQUELIBERADO, FLQUANTIDADELIBERADA, CDCONDICAOCOMERCIAL,
					VLCREDITOFRETE, VLCREDITOCONDICAO, FLPENDENTE, VLPCTDESCPROGRESSIVOMIX, QTITEMFISICODIFERENCA,
					VLVOLUMEITEM, VLPCTDESCCLIENTE, VLPCTDESCONTOCONDICAO, VLPCTDESCFRETE, CDCUPOM,
					VLPCTDESCONTOCUPOM, VLDESCONTOCUPOM, VLPCTVERBARATEIO, VLPCTMARGEMPRODUTO, CDVERBA, VLPCTCONTRATOCLI,
					FLDECISAOCALCULO, VLITEMPEDIDOSTREVERSO, VLPCTDESCONTOSTREVERSO, FLRESTRITO, FLPROMOCAO, FLVALORTABELAALTERADO,
					VLITEMIPI, VLBASEITEMIPI, QTDCREDITODESC, FLTIPOCADASTROITEM, CDPRODUTOCREDITODESC, QTITEMDESEJADO,
					VLINDICEGRUPOPROD, VLTOTALMARGEMITEM, FLSUGVENDAPERSON, VLTOTALPRECOCUSTO, VLTOTALBASESTITEM,
					VLTOTALBASEICMSITEM, QTESTOQUECLIENTE, NUDIASPRAZOENTREGA, NUCONVERSAOUNIDADEPU, VLINDICEFINANCEIROPU,
					FLDIVIDEMULTIPLICAPU, VLPCTACRESCIMOCONDICAO, VLPCTACRESCCLIENTE, VLPCTACRESCIMOICMS, VLPCTDESCONTOICMS,
					VLPCTDESCALCADA, VLALTURA, VLLARGURA, VLCOMPRIMENTO, VLPOSVINCO1, VLPOSVINCO2, VLPOSVINCO3,
					VLPOSVINCO4, VLPOSVINCO5, VLPOSVINCO6, VLPOSVINCO7, VLPOSVINCO8, VLPOSVINCO9, VLPOSVINCO10,
					CDLOCAL, FLORIGEMESCOLHAITEMPEDIDO, CDPRODUTOORIGEM, VLITEMPEDIDOORIGEM, DTINCLUSAOITEMPEDIDO,
					HRINCLUSAOITEMPEDIDO, VLPCTMARGEMAGREGADA, VLINDICECLIENTEGRUPOPROD, VLTOTALFECOPITEM, VLPCTDESCPRODUTORESTRITO,
					VLVPC, VLINDICEVOLUME, VLRETORNOPRODUTO, VLPCTDESCTIPOPEDIDO, VLDESCTIPOPEDIDO, CDLOCALESTOQUE,
					CDGRUPODESCPROD, CDGRUPODESCCLI, VLPCTDESCONTOAUTO, VLPCTDESCONTOEFETIVO, VLDESCONTOAUTO, VLTOTALDESCONTOAUTO,
					VLPCTDESCONTOAUTOEFETIVO, VLPRECOEFETIVOUNITARIO, VLPRECOEFETIVOUNITARIODESC, VLEFETIVOTOTALITEM, VLEFETIVOTOTALITEMDESC,
					VLDESCONTOTOTALAUTODESC, VLBASEINTERPOLACAOPRODUTO, FLATIVO, FLTIPOALTERACAO, DTALTERACAO, HRALTERACAO,
					QTENCOMENDA, VLTOTALENCOMENDA, VLDESCTIPOPEDIDOENCOMENDA, DTENTREGA, CDCOMISSAOPEDIDOREP,
					VLDESCONTOCONDICAO, QTESTOQUEPREVISTO, DTESTOQUEPREVISTO, VLITEMFRETETRIBUTACAO, VLTOTALITEMFRETETRIBUTACAO,
					QTFATURADA, VLPCTDESCCONDPAGTO, VLPCTTOTALMARGEMITEM, CDPACOTE, VLPCTDESCPEDIDO, 
					VLVERBAGRUPOITEM, VLBASEANTECIPACAO, VLINDICECONDICAOPAGTO, VLPONTUACAOBASEITEM, VLPONTUACAOREALIZADOITEM,
					VLPESOPONTUACAO, VLFATORCORRECAOFAIXAPRECO, VLFATORCORRECAOFAIXADIAS, VLPCTFAIXAPRECOPONTUACAO,
					VLBASEPONTUACAO, CDPOLITICACOMERCIAL, VLPCTPOLITICACOMERCIAL, FLPROMOCIONAL, VLBASECALCULODESCPROMOCIONAL,
					CDMOTIVOPENDENCIA, NUORDEMLIBERACAO, VLTOTALMAODEOBRA, VLTOTALIMPOSTOS, VLTOTALCUSTOCOMERCIAL,
					VLTOTALCUSTOFINANCEIRO, VLTOTALCOMISSAO, CDCULTURA, CDPRAGA, VLDOSE, QTITEMGONDOLA, VLBASEMARGEMRENTAB,
					VLCUSTOMARGEMRENTAB, VLPCTMARGEMRENTAB, CDMARGEMRENTAB, VLDESCPRODUTORESTRITO, VLTOTALDESCPRODUTORESTRITO,
					VLINDICEREDMARGEM, VLBASEMARGEM
				)
				SELECT
					CDEMPRESA, CDREPRESENTANTE, FLORIGEMPEDIDO, CONCAT('A', NUPEDIDO), CDPRODUTO, FLTIPOITEMPEDIDO,
					NUSEQPRODUTO, ROW_NUMBER() OVER (ORDER BY NUSEQITEMPEDIDO), CDTABELAPRECO, CDITEMGRADE1, CDITEMGRADE2, CDITEMGRADE3,
					QTITEMFISICO, QTITEMFATURAMENTO, VLITEMPEDIDO, VLBASEITEMTABELAPRECO, VLBASEITEMPEDIDO, VLBASEFLEX,
					VLTOTALITEMPEDIDO, VLPCTDESCONTO, VLPCTACRESCIMO, VLPCTDESCONTOFOB, VLPCTIPIITEM, VLIPIITEM,
					VLRENTABILIDADE, NULISTATABELAPRECO, QTTROCAESPECIAL, VLUNIDADEPADRAO, VLBASEEMBALAGEMELEMENTAR, FLCONTROLEERP,
					DSMENSAGEMCONTROLEERP, DSMENSAGEMCONTROLEWMW, CDGRUPOBONIFICACAO, CDLINHA, VLVERBAITEM, CDCONTACORRENTE,
					CDKIT, CDLOTEPRODUTO, VLITEMPEDIDOFRETE, QTPONTOSITEM, VLPCTIPIITEMFRETE, VLIPIITEMFRETE,
					CDMOTIVOTROCA, CDUNIDADE, DSOBSMOTIVOTROCA, VLST, VLVERBAITEMPOSITIVO, QTPESO, DSOBSERVACAO,
					VLPCTCOMISSAO, FLPRECOLIBERADOSENHA, VLREDUCAOOPTANTESIMPLES, VLTOTALBRUTOITEMPEDIDO, FLORIGEMITEMPEDIDO,
					FLVENDIDOQTMINIMA, CDPRAZOPAGTOPRECO, QTITEMPEDIDOUNELEMENTAR, VLITEMPEDIDOUNELEMENTAR, FLMETAGRUPOPRODLIBERADOSENHA,
					VLFRETE, FLLIBERADOVENDARELACIONADA, QTITEMESTOQUEPOSITIVO, VLDESCONTOCCP, VLPCTDESCONTOCCP, NUPROMOCAO,
					VLFINALPROMO, VLDESCONTOPROMO, VLPCTDESCONTOPROMO, VLPCTFAIXADESCQTD, VLFECOP, VLICMS,
					VLPIS, VLCOFINS, VLDESPESAACESSORIA, VLDESCONTO, VLPCTDESCONTO2, VLDESCONTO2, VLPCTDESCONTO3, VLDESCONTO3,
					CDSUGESTAOVENDA, VLTOTALITEMPEDIDOFRETE, VLPCTDESCONTOCANAL, CDTRIBUTACAOCONFIG, DTINICIOPROMOCAO,
					CDVERBAGRUPO, VLTOTALSTITEM, VLTOTALIPIITEM, VLTOTALICMSITEM, VLTOTALPISITEM, VLTOTALCOFINSITEM,
					VLSEGUROITEMPEDIDO, CDUSUARIOLIBERACAO, FLESTOQUELIBERADO, FLQUANTIDADELIBERADA, CDCONDICAOCOMERCIAL,
					VLCREDITOFRETE, VLCREDITOCONDICAO, FLPENDENTE, VLPCTDESCPROGRESSIVOMIX, QTITEMFISICODIFERENCA,
					VLVOLUMEITEM, VLPCTDESCCLIENTE, VLPCTDESCONTOCONDICAO, VLPCTDESCFRETE, CDCUPOM,
					VLPCTDESCONTOCUPOM, VLDESCONTOCUPOM, VLPCTVERBARATEIO, VLPCTMARGEMPRODUTO, CDVERBA, VLPCTCONTRATOCLI,
					FLDECISAOCALCULO, VLITEMPEDIDOSTREVERSO, VLPCTDESCONTOSTREVERSO, FLRESTRITO, FLPROMOCAO, FLVALORTABELAALTERADO,
					VLITEMIPI, VLBASEITEMIPI, QTDCREDITODESC, FLTIPOCADASTROITEM, CDPRODUTOCREDITODESC, QTITEMDESEJADO,
					VLINDICEGRUPOPROD, VLTOTALMARGEMITEM, FLSUGVENDAPERSON, VLTOTALPRECOCUSTO, VLTOTALBASESTITEM,
					VLTOTALBASEICMSITEM, QTESTOQUECLIENTE, NUDIASPRAZOENTREGA, NUCONVERSAOUNIDADEPU, VLINDICEFINANCEIROPU,
					FLDIVIDEMULTIPLICAPU, VLPCTACRESCIMOCONDICAO, VLPCTACRESCCLIENTE, VLPCTACRESCIMOICMS, VLPCTDESCONTOICMS,
					VLPCTDESCALCADA, VLALTURA, VLLARGURA, VLCOMPRIMENTO, VLPOSVINCO1, VLPOSVINCO2, VLPOSVINCO3,
					VLPOSVINCO4, VLPOSVINCO5, VLPOSVINCO6, VLPOSVINCO7, VLPOSVINCO8, VLPOSVINCO9, VLPOSVINCO10,
					CDLOCAL, FLORIGEMESCOLHAITEMPEDIDO, CDPRODUTOORIGEM, VLITEMPEDIDOORIGEM, DTINCLUSAOITEMPEDIDO,
					HRINCLUSAOITEMPEDIDO, VLPCTMARGEMAGREGADA, VLINDICECLIENTEGRUPOPROD, VLTOTALFECOPITEM, VLPCTDESCPRODUTORESTRITO,
					VLVPC, VLINDICEVOLUME, VLRETORNOPRODUTO, VLPCTDESCTIPOPEDIDO, VLDESCTIPOPEDIDO, CDLOCALESTOQUE,
					CDGRUPODESCPROD, CDGRUPODESCCLI, VLPCTDESCONTOAUTO, VLPCTDESCONTOEFETIVO, VLDESCONTOAUTO, VLTOTALDESCONTOAUTO,
					VLPCTDESCONTOAUTOEFETIVO, VLPRECOEFETIVOUNITARIO, VLPRECOEFETIVOUNITARIODESC, VLEFETIVOTOTALITEM, VLEFETIVOTOTALITEMDESC,
					VLDESCONTOTOTALAUTODESC, VLBASEINTERPOLACAOPRODUTO, FLATIVO, FLTIPOALTERACAO, DTALTERACAO, HRALTERACAO,
					QTENCOMENDA, VLTOTALENCOMENDA, VLDESCTIPOPEDIDOENCOMENDA, DTENTREGA, CDCOMISSAOPEDIDOREP,
					VLDESCONTOCONDICAO, QTESTOQUEPREVISTO, DTESTOQUEPREVISTO, VLITEMFRETETRIBUTACAO, VLTOTALITEMFRETETRIBUTACAO,
					QTFATURADA, VLPCTDESCCONDPAGTO, VLPCTTOTALMARGEMITEM, CDPACOTE, VLPCTDESCPEDIDO, 
					VLVERBAGRUPOITEM, VLBASEANTECIPACAO, VLINDICECONDICAOPAGTO, VLPONTUACAOBASEITEM, VLPONTUACAOREALIZADOITEM,
					VLPESOPONTUACAO, VLFATORCORRECAOFAIXAPRECO, VLFATORCORRECAOFAIXADIAS, VLPCTFAIXAPRECOPONTUACAO,
					VLBASEPONTUACAO, CDPOLITICACOMERCIAL, VLPCTPOLITICACOMERCIAL, FLPROMOCIONAL, VLBASECALCULODESCPROMOCIONAL,
					CDMOTIVOPENDENCIA, NUORDEMLIBERACAO, VLTOTALMAODEOBRA, VLTOTALIMPOSTOS, VLTOTALCUSTOCOMERCIAL,
					VLTOTALCUSTOFINANCEIRO, VLTOTALCOMISSAO, CDCULTURA, CDPRAGA, VLDOSE, QTITEMGONDOLA, VLBASEMARGEMRENTAB,
					VLCUSTOMARGEMRENTAB, VLPCTMARGEMRENTAB, CDMARGEMRENTAB, VLDESCPRODUTORESTRITO, VLTOTALDESCPRODUTORESTRITO,
					VLINDICEREDMARGEM, VLBASEMARGEM
				FROM TBLVWITEMPEDIDO
				WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO
				AND CDLINHA = 'HAWA';

				DELETE FROM TBLVWITEMPEDIDO
				WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO
				AND CDLINHA = 'HAWA';

				UPDATE IPED
				SET IPED.NUSEQITEMPEDIDO = NUSEQ
				FROM (
					SELECT
						CDEMPRESA, CDREPRESENTANTE, FLORIGEMPEDIDO, NUPEDIDO, CDPRODUTO, NUSEQITEMPEDIDO,
						ROW_NUMBER() OVER (ORDER BY NUSEQITEMPEDIDO) AS NUSEQ
					FROM TBLVWITEMPEDIDO
					WHERE
						CDEMPRESA = @CDEMPRESA 
					AND CDREPRESENTANTE = @CDREPRESENTANTE
					AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
					AND NUPEDIDO = @NUPEDIDO
					AND CDLINHA <> 'HAWA'
				) IPED;

				SELECT
					@VLTOTAL = COALESCE(SUM(VLTOTALITEMPEDIDO), 0)
				FROM TBLVWITEMPEDIDO
				WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO;
					
				UPDATE TBLVWPEDIDO 
				SET VLTOTALPEDIDO = @VLTOTAL,
					VLTOTALITENS = @VLTOTAL
				WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE 
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO;

				SELECT
					@VLTOTAL = COALESCE(SUM(VLTOTALITEMPEDIDO),0)
				FROM TBLVWITEMPEDIDO
				WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = CONCAT('A', @NUPEDIDO);

				UPDATE TBLVWPEDIDO
				SET VLTOTALPEDIDO = @VLTOTAL, VLTOTALITENS = @VLTOTAL
				WHERE
					CDEMPRESA = @CDEMPRESA 
				AND CDREPRESENTANTE = @CDREPRESENTANTE 
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = CONCAT('A', @NUPEDIDO);

			END
			ELSE
			BEGIN

				SELECT
					TOP 1 @CDLINHA = CDLINHA
				FROM TBLVWITEMPEDIDO
				WHERE
					CDEMPRESA = @CDEMPRESA
				AND CDREPRESENTANTE = @CDREPRESENTANTE
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO

				UPDATE TBLVWPEDIDO 
				SET CDORGVENDA = IIF(@CDLINHA = 'HAWA', @CDORGVENDAHAWA, @CDORGVENDAFERT)
				WHERE 
					CDEMPRESA = @CDEMPRESA
				AND CDREPRESENTANTE = @CDREPRESENTANTE
				AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
				AND NUPEDIDO = @NUPEDIDO

			END

			UPDATE TBLVWPEDIDO
			SET FLENVIADOPROTOCOLO = 'S'
			WHERE
				CDEMPRESA = @CDEMPRESA 
			AND CDREPRESENTANTE = @CDREPRESENTANTE 
			AND FLORIGEMPEDIDO = @FLORIGEMPEDIDO
			AND NUPEDIDO = @NUPEDIDO;
			
		COMMIT;

		FETCH NEXT FROM SEP_PEDIDO INTO @FLORIGEMPEDIDO, @NUPEDIDO, @CDORGVENDA;
		END;
		CLOSE SEP_PEDIDO;
		DEALLOCATE SEP_PEDIDO;


	END TRY
	BEGIN CATCH
		
		SET @RETORNO = 'ERRO - ' + ERROR_MESSAGE();
		ROLLBACK TRANSACTION;
			
	END CATCH

	/* Fim da Separação dos Pedidos antes do WebService*/
    
END
